version : "3.1"
services: 
  mongodb_dialysing: 
    container_name: mongodb_dialysing
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data: